// <auto-generated />
using System;
using DataModels.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataModels.Migrations
{
    [DbContext(typeof(EMDbContext))]
    [Migration("20220804083743_RefactoredNames")]
    partial class RefactoredNames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataModels.Models.EMList", b =>
                {
                    b.Property<int>("EMListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EMListId"), 1L, 1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EMListId");

                    b.ToTable("EMLists");
                });

            modelBuilder.Entity("DataModels.Models.EMListItem", b =>
                {
                    b.Property<int>("EMListItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EMListItemId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("EMListId")
                        .HasColumnType("int");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EMListItemId");

                    b.HasIndex("EMListId");

                    b.ToTable("EMListItems");
                });

            modelBuilder.Entity("DataModels.Models.EMListItem", b =>
                {
                    b.HasOne("DataModels.Models.EMList", null)
                        .WithMany("EMListItems")
                        .HasForeignKey("EMListId");
                });

            modelBuilder.Entity("DataModels.Models.EMList", b =>
                {
                    b.Navigation("EMListItems");
                });
#pragma warning restore 612, 618
        }
    }
}
